import { library, config } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
	faGithub,
	faInstagram,
	faDiscord,
	faLinkedin,
	faTwitter,
	faJs,
	faHtml5,
	faCss3Alt,
	faReact,
	faNodeJs,
	faPython,
	faJava,
	faDocker,
	faLinux,
	faGitAlt,
	faAndroid,
	faVuejs,
} from '@fortawesome/free-brands-svg-icons'
import {
	faArrowUp,
	faArrowRight,
	faCode,
	faMobileAlt,
	faServer,
	faTools,
	faPalette,
	faCogs,
	faMobile,
	faWrench,
	faBars,
	faTimes,
	faEnvelope,
	faLaptopCode,
	faRocket,
	faStar,
	faHeart,
	faBolt,
	faFire,
	faGraduationCap,
	faTrophy,
	faPuzzlePiece,
	faChartLine,
	faGlobe,
	faDatabase,
	faCubes,
	faBullseye,
	faLeaf,
	faScaleBalanced,
	faCheck,
	faInfoCircle,
	faGear,
} from '@fortawesome/free-solid-svg-icons'
import { defineNuxtPlugin } from 'nuxt/app'

// This is important, we are going to let Nuxt worry about the CSS
config.autoAddCss = false

// Add icons to the library
library.add(
	faGithub,
	faInstagram,
	faDiscord,
	faLinkedin,
	faTwitter,
	faJs,
	faHtml5,
	faCss3Alt,
	faReact,
	faNodeJs,
	faPython,
	faJava,
	faDocker,
	faLinux,
	faGitAlt,
	faAndroid,
	faVuejs,
	faArrowUp,
	faArrowRight,
	faCode,
	faMobileAlt,
	faServer,
	faTools,
	faPalette,
	faCogs,
	faMobile,
	faWrench,
	faBars,
	faTimes,
	faEnvelope,
	faLaptopCode,
	faRocket,
	faStar,
	faHeart,
	faBolt,
	faFire,
	faGraduationCap,
	faTrophy,
	faPuzzlePiece,
	faChartLine,
	faGlobe,
	faDatabase,
	faCubes,
	faBullseye,
	faLeaf,
	faScaleBalanced,
	faCheck,
	faInfoCircle,
	faGear
)

export default defineNuxtPlugin((nuxtApp) => {
	nuxtApp.vueApp.component('font-awesome-icon', FontAwesomeIcon)
})
